### ISSUE TITLE
is selfdestruct() a global function?

### ISSUE THREAD

**Issue by amazingandyyy** [acloudfan/Blockchain-Course-Patterns#1]
in https://github.com/acloudfan/Blockchain-Course-Patterns/blob/master/contracts/SelfDestruct.sol
`selfdestruct(owner); <- what is selfdestruct()? is it global function?`

why do you just use it in the file? Thank you

**Comment by acloudfan** [comment]
Hi Andy,
the "SelfDestruct" is the name of the contract and the one that you have pointed out "selfdestruct()" is a global function ... it also has an alias "suicide()" which personally, I don't like :)
Regards
Raj
